version: '3'
services:
  aspnet-mvc-app:
    image: tranvukien125/housemvc:latest
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DBDefault=Server=sqlserver;Database=MiniPlantStore;User ID=sa;Password=Your_password123;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./scriptEXE.sql:/scriptEXE.sql
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 15 && 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -i /scriptEXE.sql
      "
